wait for boot property

diff --git a/android-28/android-wait-for-emulator b/android-28/android-wait-for-emulator
--- a/android-28/android-wait-for-emulator
+++ b/android-28/android-wait-for-emulator
@@ -5,22 +5,19 @@
 
 set +e
 
-bootanim=""
-failcounter=0
-timeout_in_sec=360
-
-until [[ "$bootanim" =~ "stopped" ]]; do
-  bootanim=`adb -e shell getprop init.svc.bootanim 2>&1 &`
-  if [[ "$bootanim" =~ "device not found" || "$bootanim" =~ "device offline"
-    || "$bootanim" =~ "running" ]]; then
-    let "failcounter += 1"
-    echo "Waiting for emulator to start"
-    if [[ $failcounter -gt timeout_in_sec ]]; then
-      echo "Timeout ($timeout_in_sec seconds) reached; failed to start emulator"
-      exit 1
+boot_completed=`adb -e shell getprop sys.boot_completed 2>&1`
+timeout=0
+until [ "X${boot_completed:0:1}" = "X1" ]; do
+    sleep 1
+    boot_completed=`adb shell getprop sys.boot_completed 2>&1 | head -n 1`
+    echo "Read boot_completed property: <$boot_completed>"
+    let "timeout += 1"
+    if [ $timeout -gt 300 ]; then
+         echo "Failed to start emulator"
+         exit 1
     fi
-  fi
-  sleep 1
 done
+
+sleep 5
 
 echo "Emulator is ready"
